### ISSUE TITLE
Language Button Enhancement

### ISSUE THREAD

**Issue by takidilmi** [202306-NEA-DZ-FEW/team-a#78]
**Task title**
Language Button Enhancement

**Task description**
The task involves enhancing the language button on our application. The enhancement includes adding an icon to the language button and making the button draggable. This will improve the user experience by making the language selection more intuitive and customizable.

**Subtasks**

1. Design an appropriate icon for the language button.

2. Implement the icon into the existing language button.

3. Make the language button draggable.

**Comment by riadhmouamnia** [comment]
@takidilmi You should go enhance your button Taki 🤣

**Comment by takidilmi** [comment]
> @takidilmi You should go enhance your button Taki 🤣

i will definitely do that 🤣 best of luck and much of love ❤️
